/////////////////////////////////////////////////////////////////////////////////
//*****************************************************************************//
//* Project      : localizations                                              *//
//* Latest Source: https://github.com/vampirsoft/localizations                *//
//* Unit Name    : Common.Tests.inc                                           *//
//* Author       : Сергей (LordVampir) Дворников                              *//
//* Copyright 2024 LordVampir (https://github.com/vampirsoft)                 *//
//* Licensed under MIT                                                        *//
//*****************************************************************************//
/////////////////////////////////////////////////////////////////////////////////

{$IF NOT DEFINED(COMMON_TESTS_INC)}
{$DEFINE COMMON_TESTS_INC}

// Если используется QuickLib (https://github.com/exilon/QuickLib),
// необходимо включить эту опцию
//{$DEFINE USE_QUICK_LIB}

// Управление исполнителями тестов, включать можно только один одновременно.
// Если ни один не включен, тесты будут исполняться в косольном режиме
//{$DEFINE USE_VCL_TESTRUNNER}
//{$DEFINE USE_MOBILE_TESTRUNNER}

// ВНИМАНИЕ!!!
// =============================================================================
// КОД СЛЕДУЮЩИЙ НИЖЕ НЕ ПРЕДНАЗНАЧЕН ДЛЯ ИЗМЕНЕНИЯ ПРОГРАММИСТОМ И
// СОДЕРЖИТ КРИТИЧЕСКИЕ НАСТРОЙКИ

{$IF NOT DEFINED(MSWINDOWS)}
  {$UNDEF USE_VCL_TESTRUNNER}
{$ENDIF MSWINDOWS}
{$IF NOT (DEFINED(USE_VCL_TESTRUNNER) OR DEFINED(USE_MOBILE_TESTRUNNER))}
  {$DEFINE CONSOLE_TESTRUNNER}
{$ENDIF CONSOLE_TESTRUNNER}

{$INCLUDE Common.inc}

{$ENDIF ~ COMMON_TESTS_INC}
